DELIMITER //
CREATE PROCEDURE ADD_TAG (
	IN ARTWORKID VARCHAR(100),
	IN ARTWORKTAGID VARCHAR(100),
	IN ARTWORKTAGNAME VARCHAR(100)
)
BEGIN
	INSERT INTO ART_TAG(TAG_ID,TAG_NAME)
	VALUES (ARTWORKTAGID,ARTWORKTAGNAME);
	
	INSERT INTO ARTWORK_ARTTAG(ART_ID,TAG_ID)
	VALUES (ARTWORKID, ARTWORKTAGID);
	
	SELECT *
	FROM ARTWORK
	WHERE ART_ID = ARTWORKID;
END //
DELIMITER;


INSERT INTO ARTWORK(ART_ID,ART_URL,ART_TITLE,ART_DESC,ARTIST_USER_ID)
VALUES (@artId, @artUrl, @artTitle, @artDesc, @userID);