DELIMITER //
CREATE PROCEDURE ART_TAG_EDIT (
	IN ARTWORKID VARCHAR(100), 
	IN ARTWORKTAGID VARCHAR(100),
	IN ARTWORKTAGNAME VARCHAR(100)
)
BEGIN
	INSERT INTO ART_TAG(TAG_ID,TAG_NAME)
	VALUES (ARTWORKTAGID,ARTWORKTAGNAME);
	
	INSERT INTO ARTWORK_ARTTAG(ART_ID,TAG_ID)
	VALUES (ARTWORKID,ARTWORKTAGID);
	
	SELECT *
	FROM ARTWORK
	WHERE ART_ID = ARTWORKID;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE ART_EDIT (
	IN ARTWORKID VARCHAR(100),
	IN ARTWORKNAME VARCHAR(100),
	IN ARTWORKDESCRIPTION TEXT(500),
	IN ARTWORKURL VARCHAR(100)
)
BEGIN
	UPDATE ARTWORK
	SET ART_TITLE = ARTWORKNAME, ART_DESC = ARTWORKDESCRIPTION, ART_URL = ARTWORKURL
	WHERE ART_ID = ARTWORKID;
	
	DELETE FROM ARTWORK_ARTTAG
	WHERE ART_ID = ARTWORKID;
	
	SELECT *
	FROM ARTWORK
	WHERE ART_ID = ARTWORKID;
END //
DELIMITER ;