SELECT	U.USERNAME, 
        U.NAME, 
        U.SURNAME, 
        U.RATING, 
        U.CITIZEN_ID, 
		U.PROFILE_URL,
        A.MIN_PRICE, 
        A.MAX_PRICE, 
        A.BIOGRAPHY
FROM PAINTPLZ_USER U, ARTIST A
WHERE U.PAINTPLZ_USER_ID = @ArtistID AND A.ARTIST_USER_ID = @ArtistID;

SELECT  W.ART_ID,
		W.ART_TITLE,
		W.ART_DESC,
		W.UPLOAD_DATE,
		W.ART_URL,
		T.TAG_ID,
		T.TAG_NAME
FROM ARTWORK W 
	LEFT JOIN ARTWORK_ARTTAG AA ON W.ART_ID = AA.ART_ID 
	LEFT JOIN ART_TAG T ON T.TAG_ID = AA.TAG_ID
WHERE W.ARTIST_USER_ID = @ArtistID
ORDER BY W.ART_ID DESC, T.TAG_ID;
