DROP TABLE IF EXISTS `PAINTPLZ_USER`;
CREATE DATABASE PAINTPLZIO;

USE PAINTPLZIO;

DROP TABLE IF EXISTS `PAINTPLZ_USER`;
CREATE TABLE `PAINTPLZ_USER` 
(
    `PAINTPLZ_USER_ID` VARCHAR(100),
    `NAME` VARCHAR(30) NOT NULL,
    `SURNAME` VARCHAR(30) NOT NULL,
    `USERNAME` VARCHAR(30) NOT NULL,
    `PASSWORD` VARCHAR(64) NOT NULL,
    `EMAIL` VARCHAR(30) NOT NULL,
    `CITIZEN_ID` VARCHAR(13) NOT NULL,
    `CARD_NUMBER` VARCHAR(16) DEFAULT NULL,
    `USER_TYPE` ENUM('artist', 'customer') DEFAULT 'customer',
	`PROFILE_URL` VARCHAR(100) DEFAULT NULL,
	CONSTRAINT UNIQUE(`USERNAME`),
    PRIMARY KEY (`PAINTPLZ_USER_ID`)
);

DROP TABLE IF EXISTS `ARTIST`;
CREATE TABLE `ARTIST`
(
	`ARTIST_USER_ID` VARCHAR(100),
    `BIOGRAPHY` TEXT(500),
    `MEMBERSHIP_STATUS` BOOL DEFAULT FALSE,
    `RATING` FLOAT(12,2) DEFAULT 0.00,
    `BANK_ACCOUNT` VARCHAR(13),
    `EXTERNAL_URL` VARCHAR(100),
    `MIN_PRICE` FLOAT(12,2) NOT NULL,
    `MAX_PRICE` FLOAT(12,2) NOT NULL,
    CHECK(`MIN_PRICE`>=0),
    CHECK(`MAX_PRICE`>=`MIN_PRICE`),
    CHECK(0<`RATING`<6),
    PRIMARY KEY (`ARTIST_USER_ID`),
	FOREIGN KEY (`ARTIST_USER_ID`) REFERENCES `PAINTPLZ_USER`(`PAINTPLZ_USER_ID`)
);

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER`
(
	`CUSTOMER_USER_ID` VARCHAR(100),
	PRIMARY KEY (`CUSTOMER_USER_ID`),
	FOREIGN KEY (`CUSTOMER_USER_ID`) REFERENCES `PAINTPLZ_USER`(`PAINTPLZ_USER_ID`)
);

DROP TABLE IF EXISTS `GALLERY`;
CREATE TABLE `GALLERY` 
(
    `GALLERY_ID` VARCHAR(100),
    `GALLERY_NAME` VARCHAR(30) NOT NULL,
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`GALLERY_ID`),
    FOREIGN KEY (`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`)
);

DROP TABLE IF EXISTS `ARTWORK`;
CREATE TABLE `ARTWORK` 
(
    `ART_ID` VARCHAR(100),
    `ART_URL` VARCHAR(100) NOT NULL,
    `ART_TITLE` VARCHAR(30) NOT NULL,
    `ART_DESC` TEXT(500) NOT NULL,
    `UPLOAD_DATE` DATETIME(2) NOT NULL,
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    `GALLERY_ID` VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (`ART_ID`),
    FOREIGN KEY (`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`),
    FOREIGN KEY (`GALLERY_ID`) REFERENCES `GALLERY`(`GALLERY_ID`)
);

DROP TABLE IF EXISTS `ART_TAG`;
CREATE TABLE `ART_TAG` 
(
    `TAG_ID` VARCHAR(100),
    `TAG_NAME` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`TAG_ID`)
);

DROP TABLE IF EXISTS `ARTWORK_ARTTAG`;
CREATE TABLE `ARTWORK_ARTTAG` 
(
    `ART_ID` VARCHAR(100) NOT NULL,
    `TAG_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ART_ID`,`TAG_ID`),
    FOREIGN KEY (`ART_ID`) REFERENCES `ARTWORK`(`ART_ID`),
    FOREIGN KEY (`TAG_ID`) REFERENCES `ART_TAG`(`TAG_ID`)
);

DROP TABLE IF EXISTS `REQUEST`;
CREATE TABLE `REQUEST` 
(
    `REQUEST_ID` VARCHAR(100),
    `REQUEST_STATUS` ENUM('drafted', 'in_review', 'accepted', 'declined') DEFAULT 'drafted',
    `BRIEF_DESC` TEXT(500) NOT NULL,
    PRIMARY KEY (`REQUEST_ID`)
);

DROP TABLE IF EXISTS `CUSTOMER_REQUEST`;
CREATE TABLE `CUSTOMER_REQUEST` 
(
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    `REQUEST_ID` VARCHAR(100) NOT NULL,
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`CUSTOMER_USER_ID`, `REQUEST_ID`, `ARTIST_USER_ID`),
    FOREIGN KEY (`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    FOREIGN KEY (`REQUEST_ID`) REFERENCES `REQUEST`(`REQUEST_ID`),
    FOREIGN KEY (`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`)
);

DROP TABLE IF EXISTS `PAINTPLZ_ADMIN`;
CREATE TABLE `PAINTPLZ_ADMIN` 
(
  `ADMIN_ID` VARCHAR(100),
  `NAME` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ADMIN_ID`)
);

DROP TABLE IF EXISTS `PAINTPLZ_TRANSACTION`;
CREATE TABLE `PAINTPLZ_TRANSACTION`
(
	`TRANS_ID` VARCHAR(100),
    `AMOUNT` FLOAT(12,2) NOT NULL,
    `STATUS` ENUM('incomplete', 'in_review', 'completed') DEFAULT 'incomplete',
    `SENDER_UID` VARCHAR(100) NOT NULL,
    `RECEIVER_UID` VARCHAR(100) NOT NULL,
    `DUE_DATE` DATETIME(2) NOT NULL,
	`TRANS_TYPE` ENUM('tcc', 'tmm') NOT NULL,
    CHECK(`AMOUNT`>0),
    PRIMARY KEY (`TRANS_ID`)
);

DROP TABLE IF EXISTS `TRANS_CC`;
CREATE TABLE `TRANS_CC`
(
	`TRANS_CC_ID` VARCHAR(100),
    `CREDITCARD_NUMBER` VARCHAR(16) NOT NULL,
    PRIMARY KEY (`TRANS_CC_ID`),
	FOREIGN KEY (`TRANS_CC_ID`) REFERENCES `PAINTPLZ_TRANSACTION`(`TRANS_ID`)
);

DROP TABLE IF EXISTS `TRANS_MM`;
CREATE TABLE `TRANS_MM` 
(
    `TRANS_MM_ID` VARCHAR(100),
    `EVIDENCE_URL` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`TRANS_MM_ID`),
	FOREIGN KEY (`TRANS_MM_ID`) REFERENCES `PAINTPLZ_TRANSACTION`(`TRANS_ID`)
);

DROP TABLE IF EXISTS `CONTRACT`;
CREATE TABLE `CONTRACT`
(
	`CONTRACT_ID` VARCHAR(100),
    `ARTIST_SIGN` VARCHAR(10) NOT NULL,
    `CUSTOMER_SIGN` VARCHAR(10) NOT NULL,
    `EDITABLE_AMOUNT` INT NOT NULL,
    `COPYRIGHT_AGREEMENT` TEXT(500) NOT NULL,
    `DESCRIPTION` TEXT(500) NOT NULL,
    `STATUS` ENUM('draft', 'active', 'review', 'finished') DEFAULT 'draft',
    `START_DATE` DATETIME(2) NOT NULL,
    `DUE_DATE` DATETIME(2) NOT NULL,
    `WAGE` FLOAT(12,2) NOT NULL,
    `DEPOSIT` FLOAT(12,2) NOT NULL,
    `PENALTY` FLOAT(12,2) NOT NULL,
	CHECK(`WAGE`>=0),
    CHECK(`DEPOSIT`>=0),
    CHECK(`PENALTY`>=0),
    PRIMARY KEY (`CONTRACT_ID`)
);

DROP TABLE IF EXISTS `CONTRACT_ARTIST_CUSTOMER`;
CREATE TABLE `CONTRACT_ARTIST_CUSTOMER`
(
	`CONTRACT_ID` VARCHAR(100) NOT NULL,
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
	FOREIGN KEY(`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`),
    FOREIGN KEY(`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    PRIMARY KEY (`CONTRACT_ID`)
);


DROP TABLE IF EXISTS `CHATROOM`;
CREATE TABLE `CHATROOM` 
(
    `CHATROOM_ID` VARCHAR(100),
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`CHATROOM_ID`),
    FOREIGN KEY (`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`),
    FOREIGN KEY (`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`)
);

DROP TABLE IF EXISTS `MESSAGE`;
CREATE TABLE `MESSAGE` 
(
    `MESSAGE_ID` VARCHAR(100),
    `SENDER_UID` VARCHAR(100) NOT NULL,
    `SEND_DATE` DATETIME(2) NOT NULL,
    `MESSAGE_TYPE` ENUM('text','image') DEFAULT 'text',
    `CHATROOM_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`MESSAGE_ID`),
    FOREIGN KEY (`SENDER_UID`) REFERENCES `PAINTPLZ_USER`(`PAINTPLZ_USER_ID`),
    FOREIGN KEY (`CHATROOM_ID`) REFERENCES `CHATROOM`(`CHATROOM_ID`)
);

DROP TABLE IF EXISTS `MESSAGE_TEXT`;
CREATE TABLE `MESSAGE_TEXT` 
(
    `MESSAGE_TEXT_ID` VARCHAR(100) NOT NULL,
    `MESSAGE_TEXT` TEXT(500) NOT NULL,
    PRIMARY KEY (`MESSAGE_TEXT_ID`),
    FOREIGN KEY (`MESSAGE_TEXT_ID`) REFERENCES `MESSAGE`(`MESSAGE_ID`)
);

DROP TABLE IF EXISTS `MESSAGE_IMG`;
CREATE TABLE `MESSAGE_IMG` 
(
    `MESSAGE_IMG_ID` VARCHAR(100) NOT NULL,
    `IMAGE_URL` VARCHAR(100) NOT NULL,
    `IMAGE_MASKED_URL` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`MESSAGE_IMG_ID`),
    FOREIGN KEY (`MESSAGE_IMG_ID`) REFERENCES `MESSAGE`(`MESSAGE_ID`)
);

DROP TABLE IF EXISTS `EDIT_REQUEST`;
CREATE TABLE `EDIT_REQUEST` 
(
    `EDIT_REQUEST_ID` VARCHAR(100),
    `EDIT_DESC` TEXT(500) NOT NULL,
    PRIMARY KEY (`EDIT_REQUEST_ID`)
);

DROP TABLE IF EXISTS `CONTRACT_EDITREQUEST`;
CREATE TABLE `CONTRACT_EDITREQUEST` 
(
    `CONTRACT_ID` VARCHAR(100) NOT NULL,
    `EDIT_REQUEST_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`CONTRACT_ID`, `EDIT_REQUEST_ID`),
    FOREIGN KEY (`CONTRACT_ID`) REFERENCES `CONTRACT`(`CONTRACT_ID`),
    FOREIGN KEY (`EDIT_REQUEST_ID`) REFERENCES `EDIT_REQUEST`(`EDIT_REQUEST_ID`)
);

DROP TABLE IF EXISTS `SEARCH_REQUEST`;
CREATE TABLE `SEARCH_REQUEST`
(
	`SEARCH_ID` VARCHAR(100),
    `SEARCH_DATE` DATETIME(2) NOT NULL,
    `MIN_RATING` FLOAT(3,2) NOT NULL,
    `MAX_RATING` FLOAT(3,2) NOT NULL,
    `MIN_PRICE` FLOAT(12,2) NOT NULL,
    `MAX_PRICE` FLOAT(12,2) NOT NULL,
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    CHECK(5>=`MIN_RATING`>=0),
    CHECK(5>=`MAX_RATING`>=0),
    CHECK(`MIN_PRICE`>=0),
    CHECK(`MAX_PRICE`>=0),
    FOREIGN KEY(`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    PRIMARY KEY (`SEARCH_ID`)
);

DROP TABLE IF EXISTS `ARTTAG_SEARCH`;
CREATE TABLE `ARTTAG_SEARCH` 
(
    `SEARCH_ID` VARCHAR(100) NOT NULL,
    `TAG_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`SEARCH_ID`, `TAG_ID`),
    FOREIGN KEY (`SEARCH_ID`) REFERENCES `SEARCH_REQUEST`(`SEARCH_ID`),
    FOREIGN KEY (`TAG_ID`) REFERENCES `ART_TAG`(`TAG_ID`)
);

DROP TABLE IF EXISTS `REVIEW`;
CREATE TABLE `REVIEW`
(
	`REVIEW_ID` VARCHAR(100),
    `SCORE` INT(1) NOT NULL,
    `REVIEW_COMMENT` VARCHAR(200),
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    `ARTIST_USER_ID` VARCHAR(100) NOT NULL,
    FOREIGN KEY(`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    FOREIGN KEY(`ARTIST_USER_ID`) REFERENCES `ARTIST`(`ARTIST_USER_ID`),
    PRIMARY KEY (`REVIEW_ID`)
);

DROP TABLE IF EXISTS `VIEW_ART`;
CREATE TABLE `VIEW_ART` 
(
    `VIEW_ART_ID` VARCHAR(100),
    `DATE_TIME` DATETIME(2) NOT NULL,
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    `ART_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`VIEW_ART_ID`),
    FOREIGN KEY (`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    FOREIGN KEY (`ART_ID`) REFERENCES `ARTWORK`(`ART_ID`)
);

DROP TABLE IF EXISTS `VIEW_GALLERY`;
CREATE TABLE `VIEW_GALLERY` 
(
    `VIEW_GALLERY_ID` VARCHAR(100),
    `DATE_TIME` DATETIME(2) NOT NULL,
    `CUSTOMER_USER_ID` VARCHAR(100) NOT NULL,
    `GALLERY_ID` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`VIEW_GALLERY_ID`),
    FOREIGN KEY (`CUSTOMER_USER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_USER_ID`),
    FOREIGN KEY (`GALLERY_ID`) REFERENCES `GALLERY`(`GALLERY_ID`)
);

DROP TABLE IF EXISTS `VERIFY`;
CREATE TABLE `VERIFY`
(
	`TRANS_MM_ID` VARCHAR(100),
    `STATUS` BOOL NOT NULL,
    `ADMIN_ID` VARCHAR(100) NOT NULL,
    FOREIGN KEY(`ADMIN_ID`) REFERENCES PAINTPLZ_ADMIN(`ADMIN_ID`),
    PRIMARY KEY (`TRANS_MM_ID`)
);

