DELIMITER //
CREATE FUNCTION GET_RATING(ARTIST_ID VARCHAR(100))
	RETURNS FLOAT(12,2)
	DETERMINISTIC
BEGIN
	DECLARE rating FLOAT(12,2);
	SELECT AVG(R.SCORE) INTO rating
	FROM REVIEW R
	WHERE R.ARTIST_USER_ID = ARTIST_ID;
	
	RETURN rating;
END //
DELIMITER ;

