SELECT	U.PAINTPLZ_USER_ID, 
        U.USERNAME, 
        U.NAME, 
        U.SURNAME, 
        U.EMAIL, 
        U.CITIZEN_ID, 
		U.PROFILE_URL,
        U.USER_TYPE,  
        A.MIN_PRICE, 
        A.MAX_PRICE, 
        A.BIOGRAPHY
FROM PAINTPLZ_USER U LEFT JOIN ARTIST A
ON U.PAINTPLZ_USER_ID = A.ARTIST_USER_ID
WHERE U.USERNAME = @Username AND U.PASSWORD = @Password;