DELIMITER //
CREATE PROCEDURE REGISTER (
	IN PAINTPLZUSERID VARCHAR(100), 
	IN USERNAME VARCHAR(30), 
	IN NAME VARCHAR(30), 
	IN SURNAME VARCHAR(30), 
	IN EMAIL VARCHAR(30), 
	IN CITIZENID VARCHAR(13), 
	IN PASSWORD VARCHAR(64), 
	IN USERTYPE ENUM('artist','customer'), 
	IN MINIMUMPRICERATE FLOAT(12,2), 
	IN MAXIMUMPRICERATE FLOAT(12,2), 
	IN BIOGRAPHY TEXT(500)
)

BEGIN
	DROP TABLE IF EXISTS T;
    CREATE TABLE T(MINIMUMPRICERATE FLOAT(12,2), MAXIMUMPRICERATE FLOAT(12,2), BIOGRAPHY TEXT(500));

    INSERT INTO T( MINIMUMPRICERATE, MAXIMUMPRICERATE, BIOGRAPHY) 
	VALUES ( MINIMUMPRICERATE, MAXIMUMPRICERATE, BIOGRAPHY);

    INSERT INTO PAINTPLZ_USER( PAINTPLZ_USER_ID, USERNAME, NAME, SURNAME, EMAIL, CITIZEN_ID, PASSWORD, USER_TYPE) 
	VALUES ( PAINTPLZUSERID, USERNAME, NAME, SURNAME, EMAIL, CITIZENID, PASSWORD, USERTYPE);

    INSERT INTO CUSTOMER( CUSTOMER_USER_ID) 
	SELECT PAINTPLZ_USER_ID 
	FROM PAINTPLZ_USER 
	WHERE PAINTPLZ_USER.PAINTPLZ_USER_ID = PAINTPLZUSERID
	AND USER_TYPE = 'customer';

    INSERT INTO ARTIST(ARTIST_USER_ID,MIN_PRICE,MAX_PRICE,BIOGRAPHY) 
	SELECT PAINTPLZ_USER_ID,MINIMUMPRICERATE,MAXIMUMPRICERATE,BIOGRAPHY 
    FROM PAINTPLZ_USER JOIN T 
	WHERE PAINTPLZ_USER.PAINTPLZ_USER_ID = PAINTPLZUSERID 
	AND USER_TYPE = 'artist';
	
	SELECT *
	FROM PAINTPLZ_USER
	WHERE PAINTPLZ_USER.PAINTPLZ_USER_ID = PAINTPLZUSERID;
END //

DELIMITER ;