DELIMITER //
CREATE TRIGGER UPDATE_RATING
BEFORE INSERT ON REVIEW R
FOR EACH ROW
BEGIN
	UPDATE ARTIST A
        SET RATING = GET_RATING(R.ARTIST_USER_ID)
        WHERE A.ARTIST_USER_ID = R.ARTIST_USER_ID
END //
DELIMITER ;